url: 'https://piscespieces.github.io'
baseurl: '/'
title: '$SMN'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - assets/css/main.css  # Exclude the raw unprocessed CSS file

